# Generated by Django 4.1 on 2024-12-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmodule", "0002_address_address2_student2_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
